// Code generated by protoc-gen-go-enum-v0.1. DO NOT EDIT.

package servicev1

func (x *RequestType) FromString(name string) bool {
	v, ok := RequestType_value[name]
	*x = RequestType(v)
	return ok
}

func (x *Module) FromString(name string) bool {
	v, ok := Module_value[name]
	*x = Module(v)
	return ok
}
